FROM ubuntu:20.04
LABEL description="Dockerfile containing basic ubuntu container " \
      author="ines@lifebit.ai"

RUN apt update && apt upgrade -y

RUN apt install -y procps libxt-dev
RUN apt install file -y

